# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

python:
  install:
    - method: pip
      requirements: [] # We will put the theme here
    - requirements: ""

# Tell Sphinx where your conf.py is
sphinx:
  configuration: source/conf.py

# Install dependencies
pre_install:
  - pip install sphinx sphinx-rtd-theme