version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

# This section tells RTD exactly what to install before building
python:
  install:
    - method: pip
      packages:
        - sphinx
        - sphinx-rtd-theme

# Tell Sphinx where your conf.py is
sphinx:
  configuration: source/conf.py